#language: c

dist: trusty
sudo: required

env:
    - CC=gcc CXX=g++
    - CC=clang CXX=clang++

before_install:
    - uname -a
    - cat /etc/issue
    - sudo apt-get update -qq
    - sudo apt-get install autoconf libtool valgrind expect libyaml-dev python3-dev python3-pip libc-ares-dev
    - sudo pip3 install PyYAML pympler WebOb dnslib
    - gcc --version
    - g++ --version
    - clang --version
    - clang++ --version
    - python3 --version

install: true

before_script: true

script:
    - make dep -j4 disable_fast_proto=true
    - sudo env PATH=$PATH make install-dep disable_fast_proto=true
    - make skull -j4
    - sudo make install-skull
    - skull build
    - skull deploy
    - sudo skull start -D

after_success: true

after_script: true

after_failure: false

notifications:
    email:
      - hyzwowtools@gmail.com
