# Config Items
# e.g.
#
#   test_item: 123
#   test_rate: 1.0
#   test_name: module
#   test_bool: true
#

latency_detection_interval: 3
latency_detection_round: 5

cleanup_delayed: 600 # Unit: second

status_interval: 5 # Unit: second
